import styles from "./Department.module.css";
export * from "./DepartmentBreadcrumb.component";
export * from "./DepartmentFormFields.component";
export * from "./DepartmentCreate.component";
export * from "./DepartmentEdit.component";
export * from "./DepartmentList.component";
export * from "./DepartmentView.component";
export * from "./DepartmentDelete.component";
export { styles };
