export const BASEURL = process.env.REACT_APP_FAKEAPI_URL;
export const SPRINGURL = process.env.REACT_APP_SPRING_URL;
export const AUTH_TOKEN_EXPIRES_AT = process.env.REACT_APP_AUTH_TOKEN_EXPIRES_AT;
export const REFRESH_TOKEN_EXPIRES_AT = process.env.REACT_APP_REFRESH_TOKEN_EXPIRES_AT;
