export * from "./ReportPatrimonyGeneralView.component";
export * from "./ReportPatrimonyLossesView.component";
export * from "./ReportPatrimonyAvailable.component";
export * from "./ReportRequestPending.component";
export * from "./ReportPatrimonyOnDepartment.component";
export * from "./ReportPatrimonyOnLoan.component";
export * from "./ReportPatrimonyByLoan.component";
export * from "./ReportMaintenceSchedule.component";
export * from "./ReportMaintenceExpenses.component";
